import type { Metadata } from 'next';
import { SITE } from '@/lib/site';

const OG_LOCALE = { fr: 'fr_FR', ar: 'ar_DZ' } as const;

/**
 * Share card generated by app/opengraph-image.tsx. Listed explicitly because a
 * page-level `openGraph` object replaces the one inherited from the root.
 */
const OG_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: `${SITE.name} — véhicules d’exception, de la France à l’Algérie`,
};

/** hreflang + canonical for a public path ('' for the home page). French is the x-default. */
export function alternates(locale: string, path: string) {
  return {
    canonical: locale === 'fr' ? path || '/' : `/${locale}${path}`,
    languages: { fr: path || '/', ar: `/ar${path}`, 'x-default': path || '/' },
  };
}

/**
 * Complete per-page metadata: title, description, canonical/hreflang, Open
 * Graph and Twitter card. The share image comes from app/opengraph-image.
 */
export function pageMeta(locale: string, path: string, title: string, description: string): Metadata {
  const loc = locale === 'ar' ? 'ar' : 'fr';
  const alt = alternates(locale, path);
  return {
    title,
    description,
    alternates: alt,
    openGraph: {
      type: 'website',
      siteName: SITE.name,
      title,
      description,
      url: alt.canonical,
      locale: OG_LOCALE[loc],
      alternateLocale: [OG_LOCALE[loc === 'fr' ? 'ar' : 'fr']],
      images: [OG_IMAGE],
    },
    twitter: { card: 'summary_large_image', title, description, images: [OG_IMAGE.url] },
  };
}

/** Turn a YouTube link into a privacy-friendly embed URL; other URLs are returned as-is. */
export function videoEmbed(url: string): { kind: 'youtube' | 'file'; src: string } {
  const m = url.match(
    /(?:youtube\.com\/(?:watch\?v=|embed\/|shorts\/)|youtu\.be\/)([\w-]{11})/
  );
  if (m) return { kind: 'youtube', src: `https://www.youtube-nocookie.com/embed/${m[1]}` };
  return { kind: 'file', src: url };
}
